"""Initial migration

Revision ID: 27dc55781c0d
Revises: 
Create Date: 2023-10-31 14:36:22.456620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27dc55781c0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('sampah', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('jenis',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('harga',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sampah', schema=None) as batch_op:
        batch_op.alter_column('harga',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('jenis',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user', '', ''), server_default=sa.text("'admin'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
